build: fix ChangeLog generation and ship tests in dist
Generate ChangeLog from full git history instead of the frozen 0.7.3
range, remove the obsolete scp release target, and include tests/test.py
in the release tarball.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -16,29 +16,30 @@ doc_DATA =                                      \
 pkgconfigdir = $(libdir)/pkgconfig
 pkgconfig_DATA = osmgpsmap-1.0.pc
 
+# Unit tests ship in the tarball (CI/git also run them in-tree).
+EXTRA_DIST = tests/test.py
+
 DISTCLEANFILES = gtk-doc.make
 
-# ChangeLog generation from nautils
+# Drop generated ChangeLog on VPATH distclean only.
 distclean-local:
 	if test "$(srcdir)" = "."; then :; else \
 		rm -f ChangeLog; \
 	fi
 
+# Build ChangeLog from full git history for dist. NEWS is the curated release notes.
 ChangeLog:
-	$(AM_V_GEN)if test -d "$(srcdir)/.git"; then \
-	  (GIT_DIR=$(top_srcdir)/.git ./missing --run git log 0.7.3.. --stat -M -C --name-status  --date=short --no-color) | fmt --split-only > $@.tmp \
+	$(AM_V_GEN)if test -d "$(top_srcdir)/.git"; then \
+	  (cd "$(top_srcdir)" && git log --stat -M -C --name-status --date=short --no-color) > $@.tmp \
 	  && mv -f $@.tmp $@ \
 	  || ($(RM) $@.tmp; \
-	      echo Failed to generate ChangeLog, your ChangeLog may be outdated >&2; \
-	      (test -f $@ || echo git-log is required to generate this file >> $@)); \
+	      echo "Failed to generate ChangeLog, your ChangeLog may be outdated" >&2; \
+	      (test -f $@ || echo "git-log is required to generate this file" >> $@)); \
 	else \
 	  test -f $@ || \
-	  (echo A git checkout and git-log is required to generate ChangeLog >&2 && \
-	  echo A git checkout and git-log is required to generate this file >> $@); \
+	  (echo "A git checkout and git-log is required to generate ChangeLog" >&2 && \
+	   echo "A git checkout and git-log is required to generate this file" >> $@); \
 	fi
-
-release: dist
-	scp @PACKAGE@-@VERSION@.tar.gz root@greenbirdsystems.com:/var/www/johnstowers.co.nz/files/osm-gps-map/
 
 .PHONY: ChangeLog
 
